# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import spaceship_pb2 as spaceship__pb2


class SpaceshipControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAccess = channel.unary_unary(
                '/spaceship.SpaceshipControl/CheckAccess',
                request_serializer=spaceship__pb2.CheckAccessRequest.SerializeToString,
                response_deserializer=spaceship__pb2.CheckAccessResponse.FromString,
                )


class SpaceshipControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceshipControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAccess,
                    request_deserializer=spaceship__pb2.CheckAccessRequest.FromString,
                    response_serializer=spaceship__pb2.CheckAccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceship.SpaceshipControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpaceshipControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceship.SpaceshipControl/CheckAccess',
            spaceship__pb2.CheckAccessRequest.SerializeToString,
            spaceship__pb2.CheckAccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
